spring:
  profiles:
    active: local # 激活的配置文件
  application:
    name: ai-passage-creator
  # MySQL 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # Redis 配置
  data:
    redis:
      host: ${HOST}
      port: 6379
      database: 0
      password: ${PASSWORD}
server:
  port: 8567
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi 配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.guyuqi.moreagent.controller
# knife4j 接口文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn
# mybatis-flex 配置
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: false

